services:
  frontend:
    image: frontend
    ports:
      - "8080:80"
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    # depends_on:
      # - backend
  # backend:
  #   image: backend
  #   build: 
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports: 
  #     - "8080:8080"
        

  # backend:
  # shortUrlDb:
