services:
  frontend:
    image: frontend
    ports:
      - "4200:80"
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - shorter-url
  shorter-url:
    image: shorter-url
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports: 
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://shorterUrlDb:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    depends_on: 
      - shorterUrlDb
  shorterUrlDb:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${BD_USER}
      POSTGRES_DATABASE: ${DB_NAME}
    restart: always
    volumnes:
      - ./backend/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
volumnes:
  postgres_data: