-- MySQL Script generated by MySQL Workbench
-- Wed May  8 01:39:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;

SET
    @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;

SET
    @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema urls
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `urls`;

-- -----------------------------------------------------
-- Schema urls
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `urls` DEFAULT CHARACTER SET utf8;

USE `urls`;

-- -----------------------------------------------------
-- Table `urls`.`urls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `urls`.`urls`;

CREATE TABLE IF NOT EXISTS `urls`.`urls` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `shorted_url` TEXT NOT NULL,
    `original_url` TEXT NOT NULL,
    `date` TIMESTAMP NOT NULL,
    `user` TEXT NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;

SET SQL_MODE = @OLD_SQL_MODE;

SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
