server.port=8080

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.shortener.base-url=${BASE_URL:https://shorter-url-be-staging.up.railway.app/shorter-url/api/url/}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200,https://shorter-url-fe-staging.up.railway.app}
